<?php
function obb_carousel_menu() {
   $items = array();
   $items['admin/config/ting/obb_carousel'] = array(
    'title' => 'Obb carousel generalt',
    'description' => 'Indstill OBB carousel indstillinger generalt',
    'page callback' => 'obb_carousel_list_admin_form',
    'page arguments' => array(),
    'access arguments' => array('configure carousel'),
    'file' => 'obb_carousel.admin.inc',
  );
  $items['obb/carousel/ajax/get/preview/%'] = array(
    'page callback' => 'obb_carousel_get_preview', // Render HTML
    'description' => 'ajax load of material preview',
     'page arguments' => array(5),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
   );

   return $items;
}
function obb_carousel_get_preview($material_id)
{
    $object = ding_entity_load($material_id, 'ting_object');  
    echo render(ting_object_view($object));
    drupal_exit();
}
/**
 * Implements hook_theme().
 */
function obb_carousel_theme() {
  return array(
    'obb_carousel' => array(
      'template' => 'templates/obb_carousel',
      'file' => 'obb_carousel.theme.inc',
      'render element' => 'carousel',
    ),
    'obb_tabbed_carousel' => array(
      'template' => 'templates/obb_tabbed_carousel',
      'file' => 'obb_carousel.theme.inc',
      'render element' => 'tabbed_carousel',
    ),
    'obb_carousel_item' => array(
      'template' => 'templates/obb_carousel_item',
      'file' => 'obb_carousel.theme.inc',
      'render element' => 'item',
    ),
    'obb_carousel_preloader' => array(
        'template' => 'templates/obb_carousel_preloader',
        'file' => 'obb_carousel.theme.inc',
    ),
    'obb_carousel_cover_lazy' => array(
        'template' => 'templates/obb_carousel_cover_lazy',
        'file' => 'obb_carousel.theme.inc',
    )
  );
}
/**
 * Implements hook_element_info().
 */
function obb_carousel_element_info() {
  $path = drupal_get_path('module', 'obb_carousel');

  $types['obb_carousel'] = array(
    '#theme' => 'obb_carousel',
    '#items' => array(),
    '#title' => '',
    '#offset' => -1,
    '#path' => '',
    '#placeholders' => 0,
    '#placeholder' => array(
      '#type' => 'markup',
      '#markup' => '<span class="icon-spinner"></span>',
    ),
    '#hidden' => FALSE,
    '#attached' => array(
      'js' => array($path . '/js/obb_carousel.js'),
      'css' => array($path . '/css/obb_carousel.css'),
    ),
  );

  $types['obb_tabbed_carousel'] = array(
    '#theme' => 'obb_tabbed_carousel',
    '#tabs' => array(),
    '#transition' => 'fade',
    '#attached' => array(
      'js' => array($path . '/js/obb_carousel.js',$path . '/js/obb_material_information.js',$path . '/js/obb_material_loader.js'),
      'css' => array($path . '/css/obb_carousel.css'),
    ),
  );

  $types['obb_carousel_item'] = array(
    '#theme' => 'obb_carousel_item',
    '#content' => '',
    '#placeholder' => FALSE,
  );
  $types['obb_carousel_preloader'] = array(
    '#theme' => 'obb_carousel_preloader',
    'render element' => 'elements',
  );

  return $types;
}
/**
 * Implements hook_ding_carousel_transitions().
 */
function obb_carousel_obb_carousel_transitions() {
  return array(
    'none' => array(
      'name' => t('No transition'),
    ),
    'fade' => array(
      'name' => t('Fade out-in'),
    ),
    'crossFade' => array(
      'name' => t('Cross fade (beta)'),
    ),
  );
}
/**
 * Get defined carousel JS transitions.
 */
function obb_carousel_transitions() {
  return module_invoke_all('obb_carousel_transitions');
}

function obb_carousel_init_settings()
{
    module_load_include('php', 'mobile_detect', 'mobile_detect');
    $detect = new Mobile_Detect();

    $settings = array();
    if( $detect->isMobile())
    {
        $settings['chunk_size'] = variable_get('obb_mobile_display_count',4);
    }
    else if($detect->isTablet())
    {
        $settings['chunk_size'] = variable_get('obb_tablet_display_count',4);
    }
    else
    {
        $settings['chunk_size'] = variable_get('obb_pc_display_count',8);
    }
    
    $settings['image_style'] = 'ting_inspiration_list_cover';
    
    return $settings;
    
}